// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Min from "../src/Min.js";

function getUser(userId) {
  return _req => Min.text(`User: ` + userId, 200, undefined);
}

function handler(req) {
  let match = Min.pathSegments(req);
  let len = match.length;
  if (len >= 3) {
    return Min.notFound();
  }
  switch (len) {
    case 0 :
      return Min.text("Hello from Min! 🌱", 304, [[
          "my-header",
          "test"
        ]]);
    case 1 :
      let match$1 = match[0];
      switch (match$1) {
        case "json" :
          return Min.json(JSON.parse(`{"foo":"bar","hello":"world"}`), undefined, undefined);
        case "status" :
          return Min.status(401, undefined);
        default:
          return Min.notFound();
      }
    case 2 :
      let match$2 = match[0];
      if (match$2 !== "user") {
        return Min.notFound();
      }
      let userId = match[1];
      return Min.get(req, getUser(userId));
  }
}

let _server = Min.serve(3000, Min.requestId(Min.logger(handler)));

export {
  getUser,
  handler,
  _server,
}
/* _server Not a pure module */
